### ISSUE TITLE
Pinch Doesnt work in iOS

### ISSUE THREAD

**Issue by st1992** [openspacelabs/react-native-zoomable-view#57]
Pinch zoom is not working for me on iOS. Any ideas?

**Comment by thomasttvo** [comment]
Could be a parent element that swallows the touch events. Try putting the zoomable view at the root component to see if it works and start ruling out which parent is affecting it.

**Comment by jgiles** [comment]
A simple fix that worked for me: I added `pointerEvents: 'none'` to the style of the `View` contained in my `ReactNativeZoomableView`.

I thought pinch-to-zoom wasn't working at all, but actually it worked if I pinched inside the view port but outside the content view (so, in the "background" when the content view was zoomed out or panned such that the background was visible in the view port).

Somehow the particular content view I put in the `ReactNativeZoomableView` was swallowing pinch-to-zoom gestures without doing anything, while pan gestures and double-tap to zoom were working normally. Since I didn't actually need any touch events in the contained view (the only needed touch interaction was the pan/zoom functionality), I disabled all touch events on that contained view via the `pointerEvents` style attribute. Afterwards, pinch-to-zoom worked whether I pinched on the content itself or in the background.
